/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload and ingest one document
         * @description Ingests TXT, DOCX, DOC or PDF once into canonical text, anchors and reference
         *     records. All arms reuse these exact objects. PDF read mode is a whole-document
         *     decision; native and OCR pages are never mixed.
         *
         *     Format is chosen by the filename extension of the multipart part (.txt, .docx,
         *     .doc, .pdf), not by media type. The filename is significant. One exception: a
         *     .doc part whose first bytes are a ZIP local file header is read as .docx. No
         *     other extension is read by content.
         *
         *     The client must state, before the first run, that OCR runs in-process, that
         *     retrieval sends model-chosen search phrases, which may contain document
         *     excerpts, to an external embedding provider, and that the selected document
         *     text is sent to the model provider for analysis.
         */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Purge a document session
         * @description Erases the document: upload bytes, canonical text and chat context, and with
         *     them every run of that document, its findings and its attempts. A finding
         *     carries the offsets, boxes and legal locators saying where in the contract the
         *     system looked, so an erasure control that kept them would mean "forget the
         *     text" rather than what it says. Every task reading the document is cancelled
         *     first -- analyses, and the routing and explaining calls a chat message starts,
         *     which hold the session and carry its text in their grounding -- so nothing goes
         *     on working over material the reader has been told is gone, and nothing files
         *     findings against records being removed. The browser sends this best-effort on
         *     close.
         *
         *     Idempotent: a document the process no longer holds is already purged, so the
         *     response is 204 whether or not it was there. Retention sweeps and restarts drop
         *     the text while a browser tab still names it, and an erasure control must not
         *     report failure in exactly that case.
         *
         *     Refused only while the final evaluation batch is sealed, when the records this
         *     would erase are the measurement in progress.
         */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ephemeral canonical blocks and anchors
         * @description Returns canonical text blocks and their anchors for rendering. TXT and Word inputs
         *     render these blocks. For PDF the original file stays in the browser as a local File
         *     object; PDF.js renders it and uses the returned boxes for overlays. The server does
         *     not claim converted Word text preserves page layout.
         */
        get: operations["getDocumentContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start one arm
         * @description Every arm accepts every document. ON supplies resolved internal-reference
         *     context where the document has any; where it has none the run is
         *     byte-identical to MID, which is a real experimental condition rather than an
         *     error. context_edge_count on the run record says which of the two happened.
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run status, findings, telemetry and content availability */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a stop
         * @description Cancellation is a request. Attempt costs already incurred are retained, and units
         *     without a terminal finding become not_processed.
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent event stream of status, counters and finding IDs
         * @description Events carry status, counters and finding IDs only. They never carry document or
         *     corpus text. Durable replay is not promised: on reconnect, fall back to GET
         *     /runs/{runId} for authoritative state.
         *
         *     The server adds run_id at serialisation time; it is not a field of RunEvent
         *     in the codebase.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send one reader message and let the system decide what it asks for
         * @description One composer, one send. The reader writes a message against a completed run and
         *     the system reads what it asks for rather than making the reader choose: a
         *     question about the analysis (ask), an objection to one finding (contest), or a
         *     request to analyse one unit again (analyse). Routing is a single model call with
         *     one commit tool and no corpus access, recorded as its own unmeasured route child
         *     run; the interaction it selects then starts exactly as if it had been chosen by
         *     hand, so a message costs one routing run plus the run of whatever it selected.
         *
         *     The router chooses targets only from identifiers the parent run already holds. An
         *     ask that names no finding is scoped to every finding on the run, which is what
         *     lets the reader ask about the analysis as a whole. A message the router cannot
         *     read commits nothing and returns message_not_routable rather than being answered
         *     as a question anyway.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/worksheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read retained worksheets */
        get: operations["getWorksheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frozen public configuration, without secrets */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Fails when the corpus is absent or fails its integrity check, the Polish OCR data
         *     is missing, the .doc converter is unavailable, or a required provider credential
         *     is not configured. `model_credential` and `embedding_credential` report only that
         *     a key is set where one is needed; neither provider is contacted to answer them.
         *     `corpus` is not free in the same way: it compares the vector space the embedding
         *     service encodes in against a probe the build recorded, which costs one embedding
         *     call the first time a process is polled and nothing on later polls. The credential
         *     is checked first, so a deployment without a key is told that rather than paying a
         *     request to find out. A run cannot start while readiness fails.
         */
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Stable machine code plus Polish user text. The code is for the client; the text is
         *     for the person. Never contains document content.
         */
        Error: {
            code: components["schemas"]["ErrorCode"];
            message_pl: string;
            /** @description Bounded structured context. Never document or corpus text. */
            detail?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Ingestion codes (unsupported_input through ocr_failed) are raised by ingest.py.
         *     Structure codes (empty_document, invalid_window, no_units) are raised by
         *     structure.py. Model-client codes (model_transport_error through
         *     model_response_schema_invalid) and the call-level budget_exhausted code are
         *     raised by the model client, under the attempt policy it applies. model_http_error is
         *     the finite representation of the dynamic model_http_<status> family; the actual
         *     HTTP status is carried in the error detail object as http_status (integer).
         *     model_identity_changed and process_restarted are raised by the storage layer.
         *     chat_citation_unknown is raised when chat cites a finding ID
         *     absent from the run. evidence_locator_unknown is raised when
         *     characterisation cites an evidence locator absent from the frozen corpus.
         *     unit_graph_recursion_exceeded records a unit cycle that exceeded its derived
         *     scheduler bound.
         *
         *     Server-layer codes (content_expired, not_found, run_already_active,
         *     run_not_finished, run_already_terminal, evaluation_batch_open,
         *     invalid_request, internal_error, dependency_unavailable) are raised by the server.
         *     invalid_request is any request-validation failure.
         *     internal_error is a defect in this server and is deliberately distinct from
         *     dependency_unavailable, which states that an external dependency is down: every
         *     operation can return 500 with the Error schema, and it is not declared per
         *     operation. dependency_unavailable is also recorded as a failed run's error
         *     code when the embedding service fails while that run is
         *     retrieving candidates: the run stops because a dependency went away, not because
         *     the server is defective. out_of_scope
         *     is raised when chat is asked to leave the explanation scope.
         *     message_not_routable is raised when the router commits no reading of a reader
         *     message: routing is one call with one commit tool and no corpus access, so
         *     silence there is a model failure rather than a question to be answered anyway.
         *
         *     Corpus-build codes (e.g. manifest_fetch_failed, article_parse_failed) are
         *     offline CLI only and deliberately excluded from this public enum.
         * @enum {string}
         */
        ErrorCode: "unsupported_input" | "empty_input" | "corrupt_input" | "limit_breach" | "missing_tool" | "conversion_failed" | "ocr_failed" | "empty_document" | "invalid_window" | "no_units" | "model_transport_error" | "model_response_invalid_envelope" | "model_response_schema_invalid" | "model_http_error" | "model_identity_changed" | "retrieval_query_empty" | "unit_graph_recursion_exceeded" | "budget_exhausted" | "chat_citation_unknown" | "evidence_locator_unknown" | "process_restarted" | "content_expired" | "not_found" | "run_already_active" | "run_not_finished" | "run_already_terminal" | "evaluation_batch_open" | "out_of_scope" | "message_not_routable" | "invalid_request" | "dependency_unavailable" | "internal_error";
        /**
         * @description Mechanism names, not quality levels. The client labels are fixed:
         *     OFF — cały dokument
         *     MID — jednostki
         *     ON — jednostki + odwołania
         * @enum {string}
         */
        ArmCode: "off" | "mid" | "on";
        /** @enum {string} */
        ReadMode: "native_pdf" | "ocr_pdf";
        /** @enum {string} */
        FindingCode: "consistent" | "contradictory" | "permissible_departure" | "no_relation" | "no_basis_found" | "basis_not_in_force" | "unit_not_adjudicable" | "not_processed" | "uncertain";
        /** @enum {string} */
        UncertainCause: "relation_below_threshold" | "force_state_undetermined" | "provision_character_undetermined" | "permitted_direction_undetermined" | "departure_direction_undetermined";
        /** @enum {string} */
        QuoteResolution: "resolved" | "quote_empty" | "quote_fabricated" | "quote_ambiguous";
        /**
         * @description The counters a run emits. A free string here is what let the browser test double
         *     drift to "units_processed" while the server emitted "processed_units" with nothing
         *     to catch it; naming them makes a mismatch a generated-type error.
         * @enum {string}
         */
        CounterName: "processed_units";
        /** @enum {string} */
        ReferenceType: "full_internal" | "relative_internal" | "directional" | "annex" | "whole_document" | "external_act";
        /** @enum {string} */
        ReferenceStatus: "resolved" | "target_does_not_exist" | "within_unit" | "ambiguous_directional" | "outside_input" | "whole_document" | "external_act";
        /**
         * @description One cross-reference detected in a unit. Every unresolved status is retained.
         *     Only resolved depth-one internal targets contribute graph context.
         */
        ReferenceRecord: {
            citing_unit_id: string;
            reference_type: components["schemas"]["ReferenceType"];
            status: components["schemas"]["ReferenceStatus"];
            raw_text: string;
            target_unit_id?: string | null;
        };
        /**
         * @description Exactly two alert levels exist plus neutral detail. contradictory and
         *     basis_not_in_force are critical. permissible_departure, uncertain and
         *     unit_not_adjudicable are warnings. consistent, no_relation and no_basis_found are
         *     neutral and MUST NOT receive a green tick, certification, or completeness wording.
         *     not_processed uses a critical document-level banner plus per-unit warning markers.
         * @enum {string}
         */
        Prominence: "critical" | "warning" | "neutral";
        /**
         * @description transport_error is the transport category. error_code distinguishes a provider
         *     or network failure (model_transport_error) from cancellation at the remaining
         *     run deadline (budget_exhausted).
         * @enum {string}
         */
        AttemptStatus: "success" | "transport_error" | "http_error" | "invalid_response" | "model_identity_changed";
        SourceAnchor: {
            start_offset: number;
            end_offset: number;
            read_mode?: components["schemas"]["ReadMode"] | null;
            block_id?: string | null;
            line_start?: number | null;
            line_end?: number | null;
            page?: number | null;
            /**
             * @description PDF page points, top-left origin. Native and OCR anchors share this space;
             *     OCR boxes are divided by the render scale before being reported.
             */
            bbox?: number[] | null;
        };
        ConversionProvenance: {
            converter: string;
            converter_version: string;
            output_hash: string;
        };
        DocumentDescriptor: {
            /** Format: uuid */
            id: string;
            content_hash: string;
            read_mode?: components["schemas"]["ReadMode"] | null;
            conversion?: components["schemas"]["ConversionProvenance"] | null;
            unit_count: number;
            /**
             * Format: date-time
             * @description Bounded session expiry. After this, content returns 410.
             */
            expires_at?: string | null;
        };
        DocumentContent: {
            /** Format: uuid */
            document_id: string;
            read_mode?: components["schemas"]["ReadMode"] | null;
            blocks: {
                /** @description Stable within one document. Readers that name their blocks keep the name; the rest are addressed by position. A finding's block_id refers to this. */
                id: string;
                text: string;
                anchor: components["schemas"]["SourceAnchor"];
            }[];
            units: components["schemas"]["Unit"][];
            /**
             * @description Cross-references detected across all units. The ON arm uses resolved
             *     references for graph context; all statuses are retained.
             */
            references: components["schemas"]["ReferenceRecord"][];
        };
        Unit: {
            id: string;
            text: string;
            anchor: components["schemas"]["SourceAnchor"];
        };
        /**
         * @description An ADMITTED legal basis, persisted with the finding and returned for stored
         *     runs as well as live ones. A rejected retrieval candidate is never presented
         *     here (RF-05 v1.4): a candidate vetoed by its provision record is reported by
         *     the finding code basis_not_in_force and its entry in legal_locators.
         *
         *     Both force records travel together and are never collapsed into one.
         *     act_force is what admits; provision_force can only veto, is undetermined in
         *     the ordinary case, and is carried through here because a consumer may not
         *     read act-scope force as provision-scope force.
         */
        LegalBasisReference: {
            provision_locator: string;
            act_identifier: string;
            act_force: components["schemas"]["ForceState"];
            provision_force: components["schemas"]["ForceState"];
            /** @enum {string} */
            character_kind: "imperative" | "dispositive" | "semi_imperative" | "undetermined";
        };
        /**
         * @description Official-source force observation with scope and provenance. On an admitted
         *     legal basis, act_force is scope act and value in_force, while provision_force
         *     is scope provision and never in_force -- a consolidated text cannot establish
         *     that a provision is in force, only that it carries an editorial repeal marker.
         */
        ForceState: {
            /** @enum {string} */
            value: "in_force" | "not_in_force" | "undetermined";
            /** @enum {string} */
            scope: "act" | "provision";
            /** Format: date */
            snapshot_date: string;
            source_locator: string;
        };
        /**
         * @description One finding for one unit. An Uncertain finding carries exactly one cause and its
         *     raw_confidence. Other codes carry neither a cause nor a raw confidence.
         *
         *     When anchor_resolved is false, the anchor property is OMITTED — not null, not
         *     partial. The client must state plainly that the anchor could not be resolved and
         *     MUST NOT approximate a position.
         *
         *     After persistence, only start_offset, end_offset, page and bbox survive from
         *     the anchor. basis is persisted with the finding and survives a reload, but it
         *     is present ONLY where a retrieval candidate was admitted; legal_locators is a
         *     tuple of locator strings and is what carries a vetoed or merely cleared
         *     candidate, which never appears as a basis.
         */
        Finding: {
            id: string;
            unit_id: string;
            code: components["schemas"]["FindingCode"];
            prominence: components["schemas"]["Prominence"];
            uncertain_cause?: components["schemas"]["UncertainCause"] | null;
            raw_confidence?: number | null;
            /**
             * @description OMITTED (not null) when anchor_resolved is false. Only start_offset,
             *     end_offset, page and bbox survive persistence.
             */
            anchor?: components["schemas"]["SourceAnchor"] | null;
            /**
             * @description False means the anchor could not be resolved. The client must say so plainly in
             *     the findings pane and MUST NOT approximate a position.
             */
            anchor_resolved?: boolean;
            /** @description The block of GET /documents/{id}/content this finding sits in, decided by the server so the client does not decide it a second way. A finding belongs to the block containing the start of its resolved anchor, and to exactly one; a finding with no resolved anchor, and any finding read after the document's retention window closes, carries null and must not be placed anywhere. */
            block_id?: string | null;
            /**
             * @description Outcome of resolving the model's citation quote against the source
             *     text. Null means resolution was never attempted for this finding --
             *     distinct from quote_empty, which means the model returned no quote.
             */
            quote_resolution?: components["schemas"]["QuoteResolution"] | null;
            /**
             * @description The ADMITTED legal basis. Persisted with the finding (FindingRecord.basis,
             *     stored as basis_json) and returned for stored runs as well as live ones.
             *     Null wherever no candidate was admitted -- including a candidate vetoed by
             *     its provision record, which RF-05 v1.4 forbids presenting as a basis.
             */
            basis?: components["schemas"]["LegalBasisReference"] | null;
            /**
             * @description Persisted locator strings for every candidate that cleared retrieval,
             *     whether or not one was admitted. This is what carries a vetoed candidate,
             *     reported alongside the basis_not_in_force finding code. It is not a
             *     fallback for basis: both can be present on the same finding.
             */
            legal_locators?: string[];
        };
        SynthesisGroup: {
            title: string;
            summary: string;
            /** @description Identifiers of findings on this same run. A grouping citing anything else is refused as an unusable model response, so each one resolves against findings. */
            finding_ids: string[];
        };
        /** @enum {string} */
        RunStatus: "running" | "completed" | "failed" | "cancelled";
        /** @enum {string} */
        EventKind: "status" | "counter" | "finding" | "worksheet";
        /** @description Per-attempt record. Prompt and response bodies are never persisted or returned. */
        AttemptTelemetry: {
            /** Format: uuid */
            id: string;
            requested_model: string;
            returned_model?: string | null;
            prompt_version: string;
            temperature: number;
            /** @description Which call unit spent this attempt. Null for run-level tasks -- the synthesis, the explainer and the question it delegates -- and for any attempt recorded before the field existed. It carries no document text, only the identifier the findings already use. */
            unit_id?: string | null;
            parameters: {
                [key: string]: unknown;
            };
            input_tokens: number;
            output_tokens: number;
            latency_ms: number;
            status: components["schemas"]["AttemptStatus"];
            retry_number: number;
            error_code?: string | null;
            prompt_hash: string;
            response_hash?: string | null;
        };
        /**
         * @description Monetary cost derived from a date-pinned price table. When no auditable table is
         *     available, monetary_cost_microunits is null and unknown_reason carries a machine
         *     code (not user prose — a client must not print it raw). When cost is known,
         *     price_table_date and price_table_hash carry the provenance.
         */
        CostRecord: {
            monetary_cost_microunits: number | null;
            /** Format: date */
            price_table_date?: string | null;
            price_table_hash?: string | null;
            /** @description Machine code validated by the storage layer. A client must not print it raw. */
            unknown_reason: string | null;
        };
        RunMetrics: {
            input_tokens: number;
            output_tokens: number;
            elapsed_ms: number;
            units_total: number;
            units_with_finding: number;
            /** @description Exact count behind the interruption banner. */
            units_not_processed: number;
            /** @description Resolved internal-reference edges the arm actually supplied as context. Always 0 for OFF and MID, which are not given any; for ON it separates a run that received context from one that ran with none because the document had none. Null for a run recorded before the count existed. */
            context_edge_count: number | null;
            finder_tool_turns?: number | null;
            finder_search_calls?: number | null;
            /** @description Requests served from the run's own retrieval cache instead of the corpus. The cache is keyed on the normalised phrase, document and corpus snapshot and lives only inside one run. It is a lower bound on repeated phrases and not a measure of repetition: two call units issuing the same phrase at once both miss, and different raw phrases can normalise to one key. Null for a run recorded before the count existed. */
            retrieval_cache_hits?: number | null;
            finder_budget_exhausted_units?: number | null;
            verifier_tool_turns?: number | null;
            provision_reads?: number | null;
            /** @description Provisions the analyst could not characterise within its turn cap, which the system closed with an undetermined character and the reason unusable_model_answer. Distinguishes a contained failure from a characterisation the analyst genuinely could not settle. */
            defaulted_characterisations?: number | null;
            cost: components["schemas"]["CostRecord"];
            attempts: components["schemas"]["AttemptTelemetry"][];
        };
        Run: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            document_id: string;
            arm: components["schemas"]["ArmCode"];
            status: components["schemas"]["RunStatus"];
            /** @description False for demo-mode runs and for any run whose parity is broken. */
            measurement_valid: boolean;
            /** Format: uuid */
            parent_run_id?: string | null;
            interaction?: ("ask" | "contest" | "analyse") | null;
            /**
             * @description True when a budget boundary was crossed. The client shows a critical
             *     document-level banner with units_not_processed.
             */
            interrupted?: boolean;
            /** @description Persisted boundary that caused an interrupted run. */
            interruption_reason?: "wall_time" | null;
            /** @description False once the document session is purged; content and chat return 410. */
            content_available: boolean;
            requested_model?: string;
            returned_model?: string | null;
            input_hash?: string;
            prompt_bundle_version?: string;
            corpus_snapshot_id?: string;
            config_version?: string;
            tool_bundle_version?: string;
            parameters?: {
                [key: string]: unknown;
            };
            retry_policy?: string;
            concurrency?: number;
            wall_budget_seconds?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            finished_at?: string | null;
            error?: components["schemas"]["Error"] | null;
            findings: components["schemas"]["Finding"][];
            /** @description Themed grouping of this run's findings, produced by the synthesis role and held for the same retention window as the document text. Null before the role has run, once the window closes, and on an installation that keeps no document text at all. */
            synthesis?: components["schemas"]["SynthesisGroup"][] | null;
            metrics: components["schemas"]["RunMetrics"] | null;
        };
        /**
         * @description Carries status, counters and finding IDs only. Never text. The server adds run_id
         *     at serialisation; it is not a field of RunEvent in the codebase.
         */
        RunEvent: {
            kind: components["schemas"]["EventKind"];
            /** @description Free snake_case status string (kind=status events only). */
            status?: string | null;
            /** @description Which counter this event carries (kind=counter events only). */
            counter_name?: components["schemas"]["CounterName"] | null;
            /** @description Counter value (kind=counter events only). */
            count?: number | null;
            /**
             * Format: uuid
             * @description Finding UUID (kind=finding events only).
             */
            finding_id?: string | null;
            /** @description Which role wrote the worksheet entry (kind=worksheet events only): one of researcher, analyst, verifier, user, system. Never what it wrote. */
            role?: string | null;
            /** @description Kind of worksheet entry appended (kind=worksheet events only). */
            entry_kind?: string | null;
            /** @description Call unit the worksheet belongs to (kind=worksheet events only). */
            unit_id?: string | null;
        };
        /**
         * @description Explanation response. When a question is out of scope, the server returns 422
         *     with error code out_of_scope rather than a ChatResponse; the client shows the
         *     refusal text from that error rather than a substitute answer.
         */
        ChatResponse: {
            answer: string;
            cited_finding_ids: string[];
            /**
             * Format: uuid
             * @description The unmeasured ask child this answer was recorded as.
             */
            interaction_run_id: string;
            /** @description Whether the answer used the frozen corpus, through a direct provision read or through the one question delegated to the researcher. */
            corpus_consulted: boolean;
        };
        WorksheetResponse: {
            /** Format: uuid */
            run_id: string;
            units: {
                unit_id: string;
                entries: {
                    [key: string]: unknown;
                }[];
            }[];
        };
        /** @description Frozen public configuration. Never contains secrets. */
        PublicConfig: {
            model_request_id: string;
            /** @description Host of the endpoint that answers a model call. The identifier does not name it, and two endpoints serving one identifier do not serve it identically, so a batch pins the host as well as the model. Host only; the credential is never served. */
            model_endpoint: string;
            prompt_bundle_version: string;
            corpus_snapshot: string;
            /** @description A hash of the vector space this deployment declares it encodes in -- the model identifier, the vector width and the pinned upstream. The model identifier alone names the model and not the space: two hosts have served one identifier and returned vectors at cosine 0.52 to each other, so a caller comparing runs needs to know whether the space is the same one. This fingerprints the declaration, so it is necessary and not sufficient; the probe vector recorded on the corpus snapshot is what compares the space that actually answered. */
            embedding_space_fingerprint: string;
            /**
             * @description Whether every act in the served corpus was read from the source format its manifest asked for. ELI serves an act's HTML and its PDF from separate routes and the HTML has failed on its own, so a build may have fallen back to the PDF. The two source formats cut an act into different units, so a fallback corpus is servable but is not the corpus the manifest describes. `unrecorded` is a snapshot built before the source formats were recorded, which cannot answer the question and is therefore not an assurance that it is clean.
             * @enum {string}
             */
            corpus_source_format: "as_declared" | "fallback" | "unrecorded";
            /** @description The policy digest every run of this deployment records, served here so a caller can tell before a run whether it faces the same tool surface and bounds as the runs it will be compared against. */
            tool_bundle_version: string;
            embedding_model: string;
            arms: components["schemas"]["ArmCode"][];
            measured_mode: boolean;
            evaluation_batch_open?: boolean;
            limits: {
                max_input_bytes: number;
                max_pdf_pages: number;
                content_ttl_seconds: number;
            };
        };
        Readiness: {
            ready: boolean;
            dependencies: {
                /** @enum {string} */
                name: "corpus" | "embedding_credential" | "ocr_language_data" | "doc_converter" | "model_credential";
                ok: boolean;
                detail?: string;
            }[];
        };
    };
    responses: {
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Content was purged by deletion, session expiry or process exit. Metadata and arm
         *     metrics for past runs remain readable.
         */
        ContentExpired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Unsupported file extension. Format is chosen by the filename extension of the
         *     multipart part (.txt, .docx, .doc, .pdf), not by media type.
         */
        UnsupportedInput: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Empty, corrupt, or not canonicalisable. */
        UnprocessableInput: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The request body or a path parameter failed validation. Every 422 on this API
         *     carries the Error schema: a RequestValidationError handler replaces FastAPI's
         *     default body so one status never carries two shapes, and the submitted value is
         *     never echoed back.
         */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Input exceeds a configured, frozen bound. */
        LimitBreach: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A required local dependency is unavailable. */
        DependencyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        DocumentId: string;
        RunId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDescriptor"];
                };
            };
            413: components["responses"]["LimitBreach"];
            415: components["responses"]["UnsupportedInput"];
            422: components["responses"]["UnprocessableInput"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Erased */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description The final evaluation batch is sealed, so the runs this would erase are
             *     the measurement in progress (evaluation_batch_open).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["InvalidRequest"];
        };
    };
    getDocumentContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentContent"];
                };
            };
            404: components["responses"]["NotFound"];
            410: components["responses"]["ContentExpired"];
            422: components["responses"]["InvalidRequest"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    document_id: string;
                    arm: components["schemas"]["ArmCode"];
                };
            };
        };
        responses: {
            /** @description Accepted; poll the run or subscribe to its events. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
            /**
             * @description Runs are concurrent by default. While the final evaluation batch is
             *     open the installation admits one active run (run_already_active).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            410: components["responses"]["ContentExpired"];
            422: components["responses"]["InvalidRequest"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidRequest"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Run already terminal. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["InvalidRequest"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description An event stream. Each event is one RunEvent as JSON in the data field.
             *     The server injects run_id into each serialised event.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["RunEvent"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["InvalidRequest"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    message: string;
                    /** @description Bounded client-held history, used to resolve what the message refers to. The router reads all of it for every intent, because "zakwestionuj to" names its target only through the turns before it; the explainer, when the message routes to ask, reads the trailing six turns. */
                    history?: {
                        /** @enum {string} */
                        role: "user" | "assistant";
                        content: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description What the message turned out to be. Exactly one of answer and run is present: answer for ask, run for the child run a contest or analyse started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        intent: "ask" | "contest" | "analyse";
                        answer?: components["schemas"]["ChatResponse"];
                        run?: components["schemas"]["Run"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Parent unfinished, or the final evaluation batch is open. Reader messages are not serialised against other work: the batch seal is what keeps a measured run alone. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            410: components["responses"]["ContentExpired"];
            /**
             * @description The router committed no reading (message_not_routable), or the selected
             *     explanation left the run's findings.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getWorksheet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored worksheet entries in unit and entry order. The list is empty for a run that analyses no unit, which is every ask child. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorksheetResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The final evaluation batch is open, or the run is still working and has not written its worksheets yet (run_not_finished). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The retention window closed, and only that: the document text or the worksheets themselves are gone. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["InvalidRequest"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
        };
    };
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ok";
                    };
                };
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Not ready; each failing dependency is named. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
